// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQoAr4F2XMtemXh9JMCs4l__6GR_w7E0',
    appId: '1:136520111175:web:219eadf47d47987d2a4d62',
    messagingSenderId: '136520111175',
    projectId: 'my-first-try-fastlane-2026',
    authDomain: 'my-first-try-fastlane-2026.firebaseapp.com',
    storageBucket: 'my-first-try-fastlane-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCin_2Gdeb_UUf5U8mUMGD7qMyplsSoero',
    appId: '1:136520111175:android:920243f566108dcb2a4d62',
    messagingSenderId: '136520111175',
    projectId: 'my-first-try-fastlane-2026',
    storageBucket: 'my-first-try-fastlane-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABJ5U1EoJQTBNOBIl-AxU1Np4EPOXx0b4',
    appId: '1:136520111175:ios:f97f9ce0b5715c9b2a4d62',
    messagingSenderId: '136520111175',
    projectId: 'my-first-try-fastlane-2026',
    storageBucket: 'my-first-try-fastlane-2026.firebasestorage.app',
    iosBundleId: 'com.example.testCiCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABJ5U1EoJQTBNOBIl-AxU1Np4EPOXx0b4',
    appId: '1:136520111175:ios:f97f9ce0b5715c9b2a4d62',
    messagingSenderId: '136520111175',
    projectId: 'my-first-try-fastlane-2026',
    storageBucket: 'my-first-try-fastlane-2026.firebasestorage.app',
    iosBundleId: 'com.example.testCiCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbQoAr4F2XMtemXh9JMCs4l__6GR_w7E0',
    appId: '1:136520111175:web:2248e0523d67edfc2a4d62',
    messagingSenderId: '136520111175',
    projectId: 'my-first-try-fastlane-2026',
    authDomain: 'my-first-try-fastlane-2026.firebaseapp.com',
    storageBucket: 'my-first-try-fastlane-2026.firebasestorage.app',
  );
}
