# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute app to firebase app distribution"
  lane :distribute do
      sh "flutter clean"
      sh "flutter build apk --release"
    firebase_app_distribution(
      app: ENV['appId'],
       firebase_cli_token: ENV['firebase_cli_token']",
      android_artifact_type: "APK",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
       testers: "toty5alouda@gmail.com , salmakhaled2599@gmail.com",
        release_notes: "Lots of amazing new features to test out!"
            )
  end
end
